2025-06-09 20:32:03,964 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: relation "tabNPS Agent Contribution" does not exist
LINE 13:     "tabNPS Agent Contribution"
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-09 20:32:26,117 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: relation "tabNPS Agent Contribution" does not exist
LINE 13:     "tabNPS Agent Contribution"
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-09 20:34:04,679 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedTable: relation "tabNPS Agent Contribution" does not exist
LINE 13:     "tabNPS Agent Contribution"
             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-09 22:33:57,573 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "FROM"
LINE 6: FROM
        ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-09 22:47:39,720 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-09 22:48:18,322 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-09 22:49:37,267 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-09 22:55:00,501 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-09 22:57:46,141 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-09 23:02:59,574 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-09 23:04:08,855 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-10 09:53:13,921 ERROR frappe New Exception collected in error log
Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
2025-06-10 11:08:07,043 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "'CGST'"
LINE 7:     item->>'cgst' AS 'CGST',
                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 11:09:15,376 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "item"
LINE 8:     item->>'igst' AS "IGST",
            ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 11:17:49,383 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'tier_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function sum(text) does not exist
LINE 11:     SUM(item->>'total_amount') AS "Tier Amount"
             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 11:36:41,938 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function jsonb_array_elements(json) does not exist
LINE 6:     jsonb_array_elements(contribution::json->'items') AS ite...
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 11:38:24,257 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function jsonb_array_elements(json) does not exist
LINE 6:     jsonb_array_elements(contribution::json->'items') AS ite...
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 11:39:40,204 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'total_calc2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.UndefinedFunction: function jsonb_array_elements(json) does not exist
LINE 6:     jsonb_array_elements(contribution::json->'items') AS ite...
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 13:32:42,942 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'date2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "SUM"
LINE 5:     SUM((item->>'cgst')::NUMERIC) AS "CGST",
            ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-10 15:56:12,538 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'join_total2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near "ORDER"
LINE 55: ORDER BY 
         ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

2025-06-11 11:28:26,568 ERROR frappe Could not take error snapshot: current transaction is aborted, commands ignored until end of transaction block

Site: NPS.local
Form Dict: {'report_name': 'join_total2', 'filters': '{}', 'ignore_prepared_report': 'false', 'are_default_filters': 'true', 'cmd': 'frappe.desk.query_report.run'}
Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 228, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 84, in generate_report_result
    res = get_report_result(report, filters) or []
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 62, in get_report_result
    res = report.execute_query_report(filters)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/core/doctype/report/report.py", line 155, in execute_query_report
    result = [list(t) for t in frappe.db.sql(self.query, filters)]
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: syntax error at or near ":"
LINE 30:         (order_details->'notes'->>'registration'):NUMERIC AS...
                                                          ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/app.py", line 116, in application
    response = frappe.api.handle(request)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 1461, in call
    return fn(*args, **newargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/__init__.py", line 693, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/desk/query_report.py", line 231, in run
    frappe.log_error("Report Error")
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 87, in log_error_snapshot
    log_error(title=str(exception), defer_insert=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/utils/error.py", line 62, in log_error
    error_log = frappe.get_doc(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/utils/__init__.py", line 217, in wrapper
    return func(*args, **kw)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 106, in get_doc
    return get_doc_from_dict(kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/document.py", line 140, in get_doc_from_dict
    controller = get_controller(data["doctype"])
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 83, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/model/base_document.py", line 94, in import_controller
    doctype_info = frappe.db.get_value("DocType", doctype, ("module", "custom", "is_tree"), as_dict=True)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 547, in get_value
    result = self.get_values(
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 663, in get_values
    out = query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/query_builder/utils.py", line 85, in execute_query
    result = frappe.local.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/postgres/database.py", line 233, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 262, in sql
    self.execute_query(query, values)
  File "/home/nikhilsrivatsa/demo/apps/frappe/frappe/database/database.py", line 357, in execute_query
    return self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

